def encoder(data):
    d,c,o=[''],'',''
    for i in data: d,c,o=(d,c+i,o)if c+i in d else(d+[c+i],'',o+str(d.index(c))+i)
    return o+(str(d.index(c)) if c else '')

def decoder(data):
    d,c,o=[''],'',''
    for i in data: d,c,o=(d,c+i,o)if i in '0123456789' else(d+[d[int(c)]+i],'',o+d[int(c)]+i)
    print (o+(d[int(c)] if c else ''))
    return o+(d[int(c)] if c else '')

#data = 'ABCDDEFGABCDEDBBDEAAEDAEDCDABC' #0A0B0C0D4E0F0G1B3D0E4B2D10A1E4A10D9A2C

#'PNBOWJPSSVNAUOWJPSSVNAUASNPHCRQDDPCRQDDPOWJPSSVNAUASNPHASNPHCRQDDPPNBASNPHPNBASNPHOWJPSSVNAUPNBOWJPSSVNAUCRQDDPASNPHPNBASNPHCRQDDPCRQDDPCRQDDPPNBPNBCRQDDPPNBPNBPNBPNBPNBPNBPNBPNBCRQDDPASNPHASNPHCRQDDPOWJPSSVNAUPNBPNBOWJPSSVNAUPNBASNPHOWJPSSVNAUOWJPSSVNAUOWJPSSVNAUPNBOWJPSSVNAUPNBOWJPSSVNAUASNPHCRQDDPCRQDDPASNPHPNBCRQDDPC**ASNPHPNBPNBASNPHOWJPSSVNAUOWJPSSVNAUCRQDDPODDPODDPO**OWJPSSVNAUASNPHCRSNPHOW**PO**UPNPHOPSSV**SNPHCRSNPHOW****DDPAUPN**'
data = 'PNBOWJPSSVNAUOWJPSSVNAUASNPHCRQDDPCRQDDPOWJPSSVNAUASNPHASNPHCRQDDPPNBASNPHPNBASNPHOWJPSSVNAUPNBOWJPSSVNAUCRQDDPASNPHPNBASNPHCRQDDPCRQDDPCRQDDPPNBPNBCRQDDPPNBPNBPNBPNBPNBPNBPNBPNBCRQDDPASNPHASNPHCRQDDPOWJPSSVNAUPNBPNBOWJPSSVNAUPNBASNPHOWJPSSVNAUOWJPSSVNAUOWJPSSVNAUPNBOWJPSSVNAUPNBOWJPSSVNAUASNPHCRQDDPCRQDDPASNPHPNBCRQDDPCRQDDPCRQDDPASNPHPNBPNBASNPHOWJPSSVNAUOWJPSSVNAUCRQDDPOWJPSSVNAUCRQDDPCRQDDPOWJPSSVNAUASNPHASNPHPNBASNPHPNBPNBPNBOWJPSSVNAUASNPHCRQDDPPNBOWJPSSVNAUOWJPSSVNAUPNBPNBCRQDDPASNPHOWJPSSVNAUCRQDDPASNPHCRQDDPPNBPNBOWJPSSVNAUASNPHCRQDDPASNPHPNBPNB'


#data = 'ABBCBCABABCAABCAABBCAA'               #0A0B2C3A2A4A6B6
#data = 'AAAAAAAAAAAAAAA'                       #0A1A2A3A4A
#data = 'ABCABCABCABCABCABC'                    #0A0B0C1B3A2C4C7A6
#data = 'ABCDDEFGABCDEDBBDEAAEDAEDCDABC'        #0A0B0C0D4E0F0G1B3D0E4B2D10A1E4A10D9A2C

#data = 'ABAABABAABAB'
#data = 'AAAAAAAAAAAAAAA'
#data = 'ABCABCABCABCABCABC'
#data = 'ABBCBCABABCAABCAABBCAAA'
#data = 'ABAABABAABABBAB'
compressed = encoder(data)
decompressed = decoder(compressed )
#decoder()